### ISSUE TITLE
Minutes-in-the-taskbar model

### ISSUE THREAD

**Issue by steve4444** [tomighty/tomighty-windows#5]
Just tried this Windows release, which fixes high DPI problems. I am a big fun  of pomodoros. Pomodoros are not timers, but a concentration technique, which helps to stay focused. Two things can reduce your ability to stay focused:

1. Audio or visual noise.
2. Not setting short term goals.

The humble physical pomodoro works, because does not steal your attention like a digital clock, but you can throw a look at its gear to understand how are you doing.    Instead, most software pomdoros do not work, because they place in front of you a giant countdown with moving seconds, which is a big visual distraction (at best). Other apps expect you to periodically manoeuvre stressful menus and check your score or wait in limbo for a ring.

Your java app was the only one to get the point in every sense. Only minutes in the taskbar: no moving seconds (it's not a formula one race), no interference with ALT-TAB, minimal space and mind intrusion, but immediate to track.

Unfortunately this Windows version, while working with high DPI, is just a timer. No one can reasonably get some job done, with it open. And, if it is hidden, it does not add much to the ordinary Windows clock.

Please, _go back to the previous minutes-in-the-taskbar model_. There are still a lot of things that you can do if you want to make your app cool, while keeping it there.

**Comment by StephenHosking** [comment]
I'm just sticking with 0.7.1, and am very (very!) happy with it. It's absolutely minimal, and does most of what you ask here: Unobtrusive, show's minutes only, only makes a brief sound at the start and end of each pom and break, has just the right "options", plus, it looks great. It doesn't require Java either.

I'm very glad that the guys are continuing to work on this brilliant app, as a few more features could be useful, but until I see something better, I'm sticking with 0.7.1

The main feature which I could use would be to name my tasks, to help me focus, so I do very much appreciate the ongoing work.

**Comment by ccidral** [comment]
@steve4444 Thanks a lot for the feedback! I definitely plan to keep the new version as close to 0.7.1 as possible concerning the existing features.
